### ISSUE TITLE
集成对外服务

### ISSUE THREAD

**Issue by XYZliang** [zhengxs2018/ai#11]
能否直接集成对外服务呢，方便外部调用。
特别是对混元、星火，目前没有看到其他的转为 openai 格式 api 的开源项目

**Comment by XYZliang** [comment]
抱歉，已经看到了 one-api 项目

**Comment by zhengxs2018** [comment]
> 抱歉，已经看到了 one-api 项目

没事，one-api 也挺不错的，我也关注了。

如果是做对外服务，那不只是格式转换，还有速率限制，apikey 自动切换，比较麻烦，而且做服务就得考虑部署和定制，不像插件那样自动发布。

而且我和朋友在搞 IDE 插件，所以服务这块没什么兴趣。
