### ISSUE TITLE
可以把异常抛出来么。通义千问流式，异常无法获取

### ISSUE THREAD

**Issue by qietugou** [zhengxs2018/ai#12]

**Comment by qietugou** [comment]
比如 https://help.aliyun.com/zh/dashscope/developer-reference/return-status-code-description

**Comment by zhengxs2018** [comment]
可以的，我看看这么兼容

**Comment by zhengxs2018** [comment]
安装下 0.6.2 版本，已经支持了。

<img width="577" alt="image" src="https://github.com/zhengxs2018/ai/assets/7506913/53b61e6c-d08a-41a4-af0a-51196cd6b1a5">


不过，qwen 启用 stream 后，给的错误也是 sse 格式的，绝了。

```
id:1
event:error
HTTP_STATUS/429 TOO_MANY_REQUESTS
data:{"code":"Throttling.AllocationQuota","message":"Free allocated quota exceeded.","request_id":"a734-xxx-2254f8"}
```

- #13
