### ISSUE TITLE
如果想调用，阿里云百炼里我的应用的api应该怎么配置。就是可以连接知识库的应用。

### ISSUE THREAD

**Issue by jyxinye** [zhengxs2018/ai#14]

**Comment by zhengxs2018** [comment]
我没做自定义路径支持，而且阿里云的比较推荐走 OpenAI 的。

https://help.aliyun.com/zh/model-studio/developer-reference/compatibility-of-openai-with-dashscope/

> 现在阿里云，讯飞都开始提供兼容 OpenAI 协议的接口，你可以试试官方的，以后这个模块可能不再维护了。
