### ISSUE TITLE
通义万象的错误异常返回字段取错了

### ISSUE THREAD

**Issue by qietugou** [zhengxs2018/ai#8]
<img width="508" alt="image" src="https://github.com/zhengxs2018/ai/assets/20251788/f8ac3b38-f035-4f7e-b07a-97739b50d11a">

**Comment by zhengxs2018** [comment]
我下班后看下

**Comment by zhengxs2018** [comment]
@qietugou 最近事情多忘记了，已经在 0.5.1 上修复了，的确是取错了
